name: Maven Package upon a push

on:
  push:
    branches:
      - '!release-branch'
      - release-1*
      - master
      - 1.0.*
      - develop
      - 1.1.*
      - MOSIP-11719
      - 1.2.*

jobs:
  build-admin-ui:
    uses: syedsalman3753/kattu/.github/workflows/npm-build.yml@master
    with:
      SERVICE_LOCATION: admin-ui
      SERVICE_NAME: admin-ui

  build-docker-admin-ui:
    needs: build-admin-ui
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'admin-ui'
            SERVICE_NAME: 'admin-ui'
            NPM_BUILD: true
            ZIP_FILENAME: 'admin-ui'
    uses: syedsalman3753/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      NPM_BUILD: ${{ matrix.NPM_BUILD }}
      ZIP_FILENAME: ${{ matrix.ZIP_FILENAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}

  sonar-analysis:
    needs: build-admin-ui
    uses: syedsalman3753/kattu/.github/workflows/npm-sonar-analysis.yml@master
    with:
      SERVICE_LOCATION: admin-ui
    secrets:
      SONAR_TOKEN: 'xxxx'
      ORG_KEY: 'xxxx'